site_name: PembrokePSutilities
repo_url: https://github.com/jpsider/PembrokePSutilities
theme: readthedocs
pages:
- Home: index.md
- PembrokePSutilities Basics:
  - What is PembrokePSutilities: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Basic Commands:
- Examples:
- Acknowledgements: acknowledgements.md
